# Laboratorio 4: Método Simplex y sus Variaciones

Santiago Casasbuenas - 202214932

Amalia Carbonell - 202122079 

## Problema 1: Implementación del Método Simplex Estándar

Implementar el método Simplex estándar para resolver el siguiente problema de programación lineal:

Maximizar:  
$$
Z = 3x_1 + 2x_2 + 5x_3 
$$

Sujeto a:  
$$
x_1 + x_2 + x_3 \leq 100  \\
2x_1 + x_2 + x_3 \leq 150 \\
x_1 + 4x_2 + 2x_3 \leq 80
$$

Con:  
$$
x_1, x_2, x_3 \geq 0 
$$



## Problema 2: Implementación del Método Simplex Dual Phase

Minimizar
$$
Z = 5x_1 - 4x_2 + 3x_3
$$

sujeto a 
$$
2x_1 + x_2 - x_3 = 10 \\
x_1 - 3x_2 + 2x_3 \geq 5 \\
x_1 + x_2 + x_3 \leq 15\\
x_1, x_2, x_3 \geq 0
$$


### Instrucciones:

#### 1. Convertir el problema a la forma estándar, transformando la minimización en maximización, convirtiendo las desigualdades en igualdades mediante variables de holgura y/o exceso, y asegurando que los términos independientes sean no negativos.

##### 1.1 Convertir el problema en forma estándar
Multiplicamos ambos lados de la ecuacion por -1 para obtener un problema de maximización:

Minimizar: $Z = 5x_1 - 4x_2 + 3x_3$ 

Maximizar: $Z^{'} = -5x_1 + 4x_2 - 3x_3$

##### 1.2 Convertir todas las restricciones a igualdades

- **Para las restricciones `≤`**: Agregamos variables de holgura.
- **Para las restricciones `≥`**: Agregamos variables de exceso y artificiales.
- **Para las restricciones `=`**: Agregamos variables artificiales si no se puede construir una SBF directamente.

**Restricción 1 original:** 

$$2x_1 + x_2 - x_3 = 10$$

Agregamos una variable artificial $a_1$ para poder formar una base:

$$2x_1 + x_2 - x_3 + a_1 = 10$$

**Restricción 2 original:**

$$x_1 - 3x_2 + 2x_3 \geq 5 $$

Convertimos en una igualdad a partir de restar una variable de exceso $e_1$ y sumar una variable artificial $a_2$:

$$x_1 - 3x_2 + 2x_3 - e_1 + a_2 = 5 $$

**Restricción 3 original:**

$$x_1 + x_2 + x_3 \leq 15$$

Añadimos una variable de holgura $s_1$:

$$x_1 + x_2 + x_3 + s_1 = 15$$


**Nuevas restricciones:**

$$
2x_1 + x_2 - x_3 + a_1 = 10 \\
x_1 - 3x_2 + 2x_3 - e_1 + a_2 = 5 \\
x_1 + x_2 + x_3 + s_1 = 15
$$

##### 1.3 Asegurar que los términos independientes sean no negativos

Todas las ecuaciones son positivas al lado derecho, por lo cual, no se debe hacer ninguna transformación.

Por lo tanto, nuestro nuevo problema se ve de la siguiente forma:

**Maximizar:**

$$
Z^{'} = -5x_1 + 4x_2 - 3x_3
$$

**Sujeto a:**

$$
2x_1 + x_2 - x_3 + a_1 = 10 \\
x_1 - 3x_2 + 2x_3 - e_1 + a_2 = 5 \\
x_1 + x_2 + x_3 + s_1 = 15 \\
x_1, x_2, x_3, s_1, e_1, a_1, a_2 \geq 0
$$

#### 2. Implementar el algoritmo del método Simplex de Dos Fases desde cero en Python

Nuestro objetivo es minimizar la suma de las variables artificiales:

**Minimizar**
$$
W  = a_1 + a_2
$$



Podemos hacerlo como problema de maximización usando:

**Maximizar**
$$
-W = -a_1 -a_2
$$

Código:

In [1]:
import numpy as np

# Variables: x1, x2, x3, s1, e1, a1, a2
# Orden:     x1 x2 x3 s1 e1 a1 a2 RHS
n_vars = 7  # Número de variables (sin incluir RHS)
tableau = []

# R1: 2x1 + x2 - x3 + a1 = 10
tableau.append([2, 1, -1, 0, 0, 1, 0, 10])

# R2: x1 - 3x2 + 2x3 - e1 + a2 = 5
tableau.append([1, -3, 2, 0, -1, 0, 1, 5])

# R3: x1 + x2 + x3 + s1 = 15
tableau.append([1, 1, 1, 1, 0, 0, 0, 15])

# Función objetivo auxiliar (W = a1 + a2 → -W = -a1 - a2)
# Notamos que las variables artificiales tienen coeficiente -1
# Luego ajustamos para que la fila Z represente la suma negativa de las filas artificiales
Z_row = [0] * (n_vars + 1)  # inicializar fila objetivo con ceros (sin RHS aún)
for i in range(2):  # artificiales están en las dos primeras filas
    for j in range(n_vars + 1):
        Z_row[j] -= tableau[i][j]  # restar la fila para formar el -W
tableau.append(Z_row)

# Convertir a array para facilitar operaciones
tableau = np.array(tableau, dtype=float)

# Mostrar tableau inicial
print("Tableau Inicial (Fase I):")
print(tableau)


Tableau Inicial (Fase I):
[[  2.   1.  -1.   0.   0.   1.   0.  10.]
 [  1.  -3.   2.   0.  -1.   0.   1.   5.]
 [  1.   1.   1.   1.   0.   0.   0.  15.]
 [ -3.   2.  -1.   0.   1.  -1.  -1. -15.]]


## Problema 3: Comparación de Rendimiento con GLPK/Pyomo

## Problema 4: Análisis de Sensibilidad en Programación Lineal